# Game types to randomly choose from
GAME_TYPES = [
    "2D platformer",
    "puzzle game",
    "memory card game",
    "snake game",
    "breakout/brick breaker",
    "tic-tac-toe with AI",
    "space shooter",
    "maze game",
    "whack-a-mole",
    "simon says memory game",
    "color matching game",
    "number guessing game",
    "rock paper scissors",
    "bubble shooter",
    "word scramble game",
    "hangman",
    "chess",
    "checkers",
    "sudoku",
    "crossword puzzle",
    "minesweeper",
    "flappy bird clone",
    "endless runner",
    "racing game (top-down or side-view)",
    "platform fighting game",
    "tower defense",
    "clicker/idle game",
    "2048 number merge",
    "connect four",
    "battleship",
    "typing speed game",
    "trivia quiz game",
    "doodle jump clone",
    "pong",
    "air hockey",
    "pinball",
    "platform adventure (Metroidvania-lite)",
    "stealth/avoidance game",
    "word search",
    "hidden object game",
    "turn-based RPG battle",
    "text adventure / interactive fiction",
    "roguelike dungeon crawler",
    "city builder (simplified)",
    "card battle game (like Hearthstone-lite)",
    "asymmetric multiplayer party game",
    "social deduction / bluffing games",
    "cooperative survival sandbox",
    "procedural storytelling RPG",
    "narrative branching episodic adventure",
    "rhythm / music-action games",
    "beat 'em up brawler",
    "physics-based sandbox",
    "vehicle & transport simulation management",
    "open-world exploration (minimalist/low-poly)",
    "emergent-economy market simulator",
    "rogue-lite deckbuilder systems",
    "merge & match puzzle systems",
    "crafting & automation factory sim",
    "time-management / service rush games",
    "escape-room puzzle series",
    "emergent systems sandbox (agents + rules)",
    "AI-companion training / life sim",
    "asynchronous turn-based (play-by-mail) games",
    "micro-strategy (small-map tactics)",
    "empire-building strategy (simplified)",
    "party mini-games collection",
    "competitive arena tactics",
    "procedural puzzle generator games",
    "brain-training / cognitive mini-games",
    "educational coding-puzzle experiences",
    "visual novel with branching mechanics",
    "hybrid tabletop-to-digital adaptations",
    "card-drafting engine games",
    "tile-placement strategy games",
    "resource-trade & diplomacy sims",
    "psychological / atmospheric horror-lite",
    "stealth infiltration puzzle",
    "parkour / flow-movement challenges",
    "precision-timing rhythm platformer",
    "dynamic-world (weather + ecosystem) sim",
    "procedural music-composer sandbox",
    "light-and-shadow puzzle games",
    "color-blend creative puzzles",
    "gesture / micro-interaction mobile microgames",
    "asymmetric co-op heist planning",
    "heist planning & execution sim",
    "modular robotics / programming puzzles",
    "non-euclidean / mind-bending puzzles",
    "memory-palace exploration games",
    "ambient exploration & relaxation (walking sim)",
    "photography & collection quest",
    "museum curator / exhibition design sim",
    "language-learning interactive adventure",
    "historical timeline-builder simulations",
    "virtual ecosystem / evolution sim",
    "economics & market-manipulation sandbox",
    "procedural theatre / improv acting sim",
    "tower-offense (reverse tower defense)",
    "short-round competitive survival (battle-royale-lite)",
    "asymmetric capture-and-escape matches",
    "co-op puzzle-platformer (team mechanics)",
    "turn-based tactical squad management",
    "match-3 dungeon crawler hybrids",
    "location-based / AR scavenger hunt",
    "sensor-driven interactive experiences",
    "modding-friendly creative sandbox toolkit",
    "procedural quest generator / sandbox narrative",
    "social VR / shared-space mini-games",
    "daily-challenge microgame loop",
    "skill-chain combo trainers",
    "meta-progression hub (hub + rotating modules)",
    "logic-sequencing puzzle",
    "physics-manipulation challenge",
    "chain-reaction strategy game",
    "co-op asymmetric puzzle adventure",
    "skill-timing precision challenges",
    "isometric tactics skirmish",
    "minimalist puzzle-loop game",
    "procedural labyrinth explorer",
    "micro-sandbox with emergent rules",
    "ecosystem-balance simulator",
    "resource-mining and crafting loops",
    "short-session competitive duels",
    "team-based coordination challenges",
    "multi-path puzzle narrative",
    "gesture-drawing action games",
    "multi-layer pattern recognition puzzles",
    "reaction-test speed challenges",
    "compact grid-based strategy",
    "creative-building construction sandbox",
    "biome-expansion management sim",
    "automation-chain optimization puzzles",
    "cooperative puzzle escape scenarios",
    "lightweight economic management",
    "inventory-based survival puzzle",
    "character-ability synergy battler",
    "tactical lane-based combat",
    "environment-altering platformer",
    "tempo-based action mechanics",
    "tile-rotation and connection puzzles",
    "rule-changing puzzle systems",
    "gravity-switch platforming",
    "plan-and-execute stealth scenarios",
    "exploration-driven item discovery",
    "spatial-memory navigation games",
    "modular-structure building games",
    "event-driven strategy sim",
    "multi-agent interaction sandbox",
    "turn-based micro-duel games",
    "branching-morality adventure",
    "ecosystem-restoration game",
    "weather-influenced strategy",
    "procedural terrain survival",
    "crafting-only progression challenge",
    "hidden-pattern detection puzzles",
    "time-loop narrative systems",
    "reverse-puzzle deduction challenges",
    "minimal-control movement games",
    "skill-tree progression battlers",
    "hybrid puzzle-adventure exploration",
    "abstract combat simulator",
    "multi-character timeline management",
    "creature-raising simulation",
    "digital board-game hybrids",
    "tactical placement battle arenas",
    "multi-step logic deduction series",
    "flow-based continuous movement games",
    "data-routing programming puzzles",
    "node-connection strategy games",
    "mood-driven narrative experience",
    "portable mini-session survival",
    "creative-expression sandbox (art, music, shapes)",
    "human-behavior simulation (crowd / society)",
    "modular card-engine crafting",
    "time-management cooperative kitchen/work sims",
    "balance-and-stability physics toys",
    "variant maze-generation challenges",
    "obstacle-dodging gauntlet",
    "adaptive-difficulty challenge modes",
    "text-analysis puzzle mechanics",
    "3D spatial-rotation training",
    "multi-branch puzzle tower climb",
    "ecosystem-predator-prey simulator",
    "compact empire-expansion microgames",
    "spell-combination action game",
    "long-term settlement development",
    "brain-training multi-test series",
    "flexible-role co-op missions",
    "symbol-matching logic puzzles",
    "audio-driven puzzle mechanics",
    "discovery-and-research exploration games",
    "tactical bridge-building simulator",
    "multi-hero rotation battle arenas",
    "procedural boss-fight generator",
    "organize-and-sort challenge games",
    "constraint-based building puzzles",
    "map-reveal exploration challenges",
    "timing-and-parry combat systems",
    "dual-character synced-control puzzles",
    "environmental hazard management",
    "hybrid tower-building strategy",
    "resource-routing conveyor puzzles",
    "non-linear micro-adventures",
    "social-coordination mini-missions",
    "planet-colonization light strategy",
    "emoji/symbol-driven puzzle gameplay"
]