name: Automatic Game Generation

on:
  # schedule:
  #   - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt-get update && sudo apt-get install -y python3-dev libcairo2-dev pkg-config

      - name: Run daily tasks
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          chmod +x run_daily_tasks.sh
          ./run_daily_tasks.sh

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated game generation"
            git push
          fi
